dist: trusty
language: java
sudo: false
services:
  - mongodb
jdk:
  - openjdk11
  - openjdk13
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
install:
  - mvn clean validate
script:
  - mvn test
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e2b5f5d5c337a7af9276
    on_success: change
    on_failure: always
    on_start: never
addons:
  sonarcloud:
    organization: rrd4j
    token:
      secure: "PUUhvfJjSp9dIbrP68Po/ZXnGf5votEEzwYuau2e+i9mAQQyO3LYm6m98+tPxgw1TbujDKpqkCGDGpOOxaK7A4RetqYF4Opg3fi8JeIlXB5VuY6XRvzvSXcAhRTWtCi7L/jYDf2VX/qWRi8axKNEW8k/U+7jLBhGmufvp7p289c="
matrix:
  include:
    - jdk: openjdk8
      script:
        - mvn clean deploy -Psonar --settings deploy-settings.xml
      on:
          branch: master
